name: Release

on:
  push:
    branches: ["release"]

jobs:
  release-prebuild:
    uses: ./.github/workflows/build.yml

  release:
    runs-on: ubuntu-latest
    needs: release-prebuild
    steps:
      - uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v3 # docs https://pnpm.io/continuous-integration#github-actions
        with:
          version: 9
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm exec semantic-release

